version: '3'
services:
  web-service:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:80
    command: ["npx", "nodemon", "app.js", "-L"]
  mysql:
    image:  mysql:8.0.34
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: user_biblioteca
      MYSQL_PASSWORD: 54321
volumes:
  mysql_data: